title: Jack Full
description: Jack Full 的个人博客
url: "https://jackfull2023.github.io"
baseurl: ""

lang: zh-CN
timezone: Asia/Shanghai

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - publications.md
