title: Jack Full
description: AcademicPages publications clone
url: "https://jackfull2023.github.io"
baseurl: ""
remote_theme: academicpages/academicpages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
